"""Generate Full Cath Lab Report — Claim Check + Deny Analysis + Appeal Letter"""

from docx import Document
from docx.shared import Pt, Cm, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
import os


def set_font(run, size=14, bold=False, color=None, font_name="TH SarabunPSK"):
    run.font.name = font_name
    run.font.size = Pt(size)
    run.font.bold = bold
    if color:
        run.font.color.rgb = RGBColor(*color)
    rpr = run._element.get_or_add_rPr()
    rFonts = rpr.find(qn("w:rFonts"))
    if rFonts is None:
        rFonts = run._element.makeelement(qn("w:rFonts"), {})
        rpr.insert(0, rFonts)
    rFonts.set(qn("w:cs"), font_name)


def add_para(doc, text, size=14, bold=False, align=WD_ALIGN_PARAGRAPH.LEFT, space_after=4, color=None):
    p = doc.add_paragraph()
    p.alignment = align
    p.paragraph_format.space_after = Pt(space_after)
    p.paragraph_format.space_before = Pt(0)
    run = p.add_run(text)
    set_font(run, size, bold, color)
    return p


def add_colored_para(doc, parts, size=14, align=WD_ALIGN_PARAGRAPH.LEFT, space_after=4):
    """parts = [(text, bold, color), ...]"""
    p = doc.add_paragraph()
    p.alignment = align
    p.paragraph_format.space_after = Pt(space_after)
    p.paragraph_format.space_before = Pt(0)
    for text, bold, color in parts:
        run = p.add_run(text)
        set_font(run, size, bold, color)
    return p


def add_table(doc, headers, rows, col_widths=None):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Header
    for i, text in enumerate(headers):
        cell = table.rows[0].cells[i]
        p = cell.paragraphs[0]
        run = p.add_run(text)
        set_font(run, 13, bold=True, color=(255, 255, 255))
        from lxml import etree
        nsmap = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
        shading = etree.SubElement(cell._tc.get_or_add_tcPr(), qn("w:shd"))
        shading.set(qn("w:val"), "clear")
        shading.set(qn("w:color"), "auto")
        shading.set(qn("w:fill"), "2E74B5")

    # Data rows
    for row_data in rows:
        row = table.add_row()
        for i, text in enumerate(row_data):
            cell = row.cells[i]
            p = cell.paragraphs[0]
            run = p.add_run(str(text))
            set_font(run, 13)

    if col_widths:
        for row in table.rows:
            for i, w in enumerate(col_widths):
                row.cells[i].width = Cm(w)

    return table


def add_section_header(doc, text, level=1):
    colors = {1: (0, 51, 102), 2: (46, 116, 181), 3: (89, 89, 89)}
    sizes = {1: 18, 2: 16, 3: 14}
    add_para(doc, "", 6)
    add_para(doc, text, sizes.get(level, 14), bold=True, color=colors.get(level), space_after=6)


def add_checkpoint(doc, icon, name, status, message, extra=None):
    status_colors = {
        "PASS": (0, 128, 0),
        "WARNING": (204, 102, 0),
        "CRITICAL": (204, 0, 0),
        "OPTIMIZATION": (0, 102, 204),
    }
    color = status_colors.get(status, (0, 0, 0))

    add_colored_para(doc, [
        (f"{icon} ", False, color),
        (f"{name}", True, None),
        (f" — {status}", True, color),
    ], size=14, space_after=2)

    if message:
        add_para(doc, f"     {message}", 13, space_after=2, color=(89, 89, 89))

    if extra:
        for line in extra:
            add_para(doc, f"     {line}", 13, space_after=1, color=(89, 89, 89))

    add_para(doc, "", 2)


def generate_full_report(output_path: str):
    doc = Document()

    for section in doc.sections:
        section.top_margin = Cm(2)
        section.bottom_margin = Cm(2)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2)

    # ═══════════════════════════════════════════
    # COVER / TITLE
    # ═══════════════════════════════════════════
    add_para(doc, "", 20)
    add_para(doc, "CATH LAB CLAIM AI REPORT", 24, bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, color=(0, 51, 102))
    add_para(doc, "รายงานการตรวจสอบ Claim ห้องสวนหัวใจ", 18, align=WD_ALIGN_PARAGRAPH.CENTER, color=(46, 116, 181))
    add_para(doc, "", 10)
    add_para(doc, "AN: 69-03556", 16, bold=True, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "โรงพยาบาลพญาไทศรีราชา (11855) เขต 6 ชลบุรี", 14, align=WD_ALIGN_PARAGRAPH.CENTER, color=(89, 89, 89))
    add_para(doc, "Generated by Hospital Claim AI — March 2026", 12, align=WD_ALIGN_PARAGRAPH.CENTER, color=(150, 150, 150))
    add_para(doc, "", 30)

    # Summary box
    add_table(doc,
        ["รายการ", "ข้อมูล"],
        [
            ["ผู้ป่วย", "นาง ลังกา เทยณี"],
            ["HN / AN", "69-09349 / 69-03556"],
            ["สิทธิ์", "UCS (บัตรทอง)"],
            ["Admit → D/C", "27/02/2569 11:44 → 01/03/2569 13:00 (LOS: 2 วัน)"],
            ["DRG", "05290 — Acute MI w single vessel PTCA wo sig CCC"],
            ["RW", "8.6544"],
            ["ยอดเรียกเก็บ", "71,322 บาท"],
            ["สถานะ", "DENY (HC09, IP01, HC13)"],
            ["เงินที่ได้รับ", "0 บาท"],
            ["เงินที่หาย", "71,322 บาท"],
        ],
        col_widths=[5, 12]
    )

    doc.add_page_break()

    # ═══════════════════════════════════════════
    # PART 1: CLAIM CHECK RESULT
    # ═══════════════════════════════════════════
    add_section_header(doc, "PART 1: CLAIM CHECK RESULT — ผลตรวจ 8 Checkpoints", 1)
    add_para(doc, "AI ตรวจเคสนี้ด้วย 8 checkpoints ตาม validation rules ของ Cath Lab", 13, color=(89, 89, 89))

    # Score summary
    add_colored_para(doc, [
        ("SCORE: ", True, (0, 51, 102)),
        ("60/100", True, (204, 102, 0)),
        ("  |  Status: ", False, None),
        ("ต้องแก้ก่อนส่งใหม่", True, (204, 102, 0)),
    ], size=16, space_after=10)

    add_table(doc,
        ["ระดับ", "จำนวน", "รายละเอียด"],
        [
            ["CRITICAL", "2", "Device (HC09) + Drug Catalog (Clopidogrel)"],
            ["WARNING", "2", "CC/MCC optimization + DRG verify"],
            ["PASSED", "4", "Basic data, Dx-Proc, 16-File, Timing"],
        ],
        col_widths=[3, 2, 12]
    )

    add_para(doc, "", 10)
    add_section_header(doc, "Checkpoints Detail", 2)

    # Checkpoints
    add_checkpoint(doc, "✅", "CP1: Basic Data", "PASS",
        "AN ✓ | HN ✓ | CID 13 หลัก ✓ | วันที่ถูกต้อง ✓ | LOS = 2 วัน")

    add_checkpoint(doc, "✅", "CP2: Dx-Proc Match", "PASS",
        "DRG 05290 = Acute MI + PCI → PDx (I21.x) + Proc (36.06) match ถูกต้อง")

    add_checkpoint(doc, "🔴", "CP3: Device Documentation", "CRITICAL",
        "HC09 = อุปกรณ์/อวัยวะเทียม documentation ไม่ครบ | INST 31,490 บาท ถูกปฏิเสธ",
        [
            "สาเหตุ: ADP file CODE/Lot#/TYPE อาจไม่ตรง",
            "แก้: ตรวจ ADP → CODE ตรง สปสช. + Lot# ตรง GPO VMI + TYPE=5",
        ])

    add_checkpoint(doc, "✅", "CP4: 16-File Completeness", "PASS",
        "ข้อมูลส่งเข้า e-Claim ได้ (มี REP กลับมา)")

    add_checkpoint(doc, "✅", "CP5: Timing & Auth", "PASS",
        "LOS = 2 วัน ✓ | ส่งภายในกำหนด ✓ | Authen Code ✓")

    add_checkpoint(doc, "💡", "CP6: CC/MCC Optimization", "OPTIMIZATION",
        "DRG 05290 (wo CCC) → ถ้าเพิ่ม CC/MCC → DRG 05291 = +23,594 บาท",
        [
            "ตรวจ: EF <40%? → เพิ่ม I50.21 (MCC)",
            "ตรวจ: DM? → เปลี่ยน E11.9 → E11.65 (CC)",
            "ตรวจ: eGFR? → เพิ่ม N18.3/N18.4 (CC/MCC)",
        ])

    add_checkpoint(doc, "🟡", "CP7: DRG Verification", "WARNING",
        "DRG 05290: RW 8.6544 | WtLOS 3.57 | OT 11 วัน → LOS 2 ปกติ",
        ["⚠️ ถ้ามี CC/MCC ที่ยังไม่ code → DRG ควรเป็น 05291 (RW 11.4820)"])

    add_checkpoint(doc, "🔴", "CP8: Drug/Lab Catalog", "CRITICAL",
        "CLOPIDOGREL_DRUG ถูกปฏิเสธ — TMT code ไม่ตรง Drug Catalogue",
        ["แก้: ตรวจ HospDrugCode → TMT mapping ใน drug.nhso.go.th"])

    doc.add_page_break()

    # ═══════════════════════════════════════════
    # PART 2: DENY ANALYSIS
    # ═══════════════════════════════════════════
    add_section_header(doc, "PART 2: DENY ANALYSIS — วิเคราะห์สาเหตุ Deny", 1)

    add_table(doc,
        ["หัวข้อ", "ผลวิเคราะห์"],
        [
            ["Category", "Device Documentation + Drug Catalog Mismatch"],
            ["Severity", "HIGH (71,322 บาท)"],
            ["Recovery Chance", "85%"],
            ["Recommended Action", "AUTO_FIX — แก้ข้อมูลแล้วส่งใหม่"],
            ["Confidence", "88%"],
        ],
        col_widths=[4, 13]
    )

    add_para(doc, "", 10)
    add_section_header(doc, "Deny Codes Explained", 2)

    add_table(doc,
        ["รหัส", "ความหมาย", "สาเหตุ", "วิธีแก้"],
        [
            ["HC09", "อุปกรณ์/อวัยวะเทียม", "ADP file CODE/Lot# ไม่ตรง", "ตรวจ ADP + GPO VMI"],
            ["HC13", "เงื่อนไข HC เพิ่มเติม", "เอกสาร device ไม่ครบ", "ส่งเอกสารเพิ่ม"],
            ["IP01", "การจ่าย IP ในเขต", "ถูก deny พ่วง HC09", "แก้ HC09 แล้วจะผ่าน"],
            ["CLOPI...", "Drug Catalog Mismatch", "TMT code ไม่ตรง", "แก้ mapping ใน Drug Catalogue"],
        ],
        col_widths=[2, 4, 4, 7]
    )

    add_para(doc, "", 10)
    add_section_header(doc, "Action Plan", 2)

    steps = [
        ("1. แก้ ADP file (HC09)", "เปิด ADP → ตรวจ TYPE=5, CODE ตรง สปสช., Lot# ตรง GPO VMI, Qty ตรง Cath report"),
        ("2. แก้ Drug Catalog", "เข้า drug.nhso.go.th → ตรวจ Clopidogrel TMT mapping → แก้ HospDrugCode → TMTID"),
        ("3. เพิ่ม CC/MCC (optional)", "เปิด chart → DM/HF/CKD/AF → เพิ่ม SDx → DRG 05290 → 05291 (+23,594 บาท)"),
        ("4. Generate 16-file ใหม่", "Export จาก SSB/HIS → ตรวจอีกรอบ → Upload e-Claim"),
    ]
    for title, desc in steps:
        add_para(doc, title, 14, bold=True, space_after=2)
        add_para(doc, f"   {desc}", 13, color=(89, 89, 89), space_after=6)

    add_para(doc, "", 6)

    # Revenue impact
    add_section_header(doc, "Revenue Impact", 2)
    add_table(doc,
        ["Scenario", "DRG", "RW", "Payment (บาท)", "ผลต่าง"],
        [
            ["ตอนนี้ (DENY)", "05290", "8.6544", "0", "-71,322"],
            ["ถ้าแก้ HC09+Drug", "05290", "8.6544", "72,264", "+72,264"],
            ["ถ้าแก้ + เพิ่ม CC/MCC", "05291", "11.4820", "95,858", "+95,858"],
        ],
        col_widths=[4, 2, 2, 4, 4]
    )

    doc.add_page_break()

    # ═══════════════════════════════════════════
    # PART 3: APPEAL LETTER
    # ═══════════════════════════════════════════
    add_section_header(doc, "PART 3: หนังสืออุทธรณ์ (Appeal Letter)", 1)
    add_para(doc, "หนังสือฉบับนี้พร้อมใช้งาน — ให้แพทย์ตรวจ clinical content → ผอ. เซ็น → ส่ง สปสช. เขต 6", 13, color=(89, 89, 89))
    add_para(doc, "", 10)

    # Formal letter
    add_para(doc, "ที่ พศ.11855/...........", 14)

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = p.add_run("โรงพยาบาลพญาไทศรีราชา\n222 หมู่ 4 ถ.สุขุมวิท ต.ศรีราชา\nอ.ศรีราชา จ.ชลบุรี 20110")
    set_font(run, 14)

    add_para(doc, "วันที่ .......... มีนาคม 2569", 14, align=WD_ALIGN_PARAGRAPH.RIGHT)
    add_para(doc, "", 6)

    add_para(doc, "เรื่อง  ขอทบทวนผลการตรวจสอบการขอรับค่าใช้จ่ายเพื่อบริการสาธารณสุข", 14, bold=True)
    add_para(doc, "เรียน  ผู้อำนวยการสำนักงานหลักประกันสุขภาพแห่งชาติ เขต 6 ระยอง", 14, bold=True)
    add_para(doc, "", 6)

    add_para(doc,
        "        ตามที่โรงพยาบาลพญาไทศรีราชา รหัสหน่วยบริการ 11855 ได้ส่งข้อมูลการขอรับค่าใช้จ่าย"
        "เพื่อบริการสาธารณสุข สำหรับผู้ป่วย", 14)

    add_table(doc,
        ["รายการ", "ข้อมูล"],
        [
            ["HN / AN", "69-09349 / 69-03556"],
            ["เลขประจำตัวประชาชน", "2411300021503"],
            ["วันที่รับเข้า — จำหน่าย", "27 ก.พ. 2569 — 1 มี.ค. 2569"],
            ["การวินิจฉัย", "I21.0 Acute transmural MI of anterior wall"],
            ["หัตถการ", "36.06 Coronary stent insertion\n37.22 Left heart cath\n88.56 Coronary angiography"],
            ["DRG / RW", "05290 / 8.6544"],
            ["ยอดเรียกเก็บ", "71,322.00 บาท"],
        ],
        col_widths=[5, 12]
    )

    add_para(doc, "", 6)
    add_para(doc,
        "        ทางโรงพยาบาลได้รับแจ้งว่าข้อมูลดังกล่าวไม่ผ่านการตรวจสอบ "
        "โดยรหัสปฏิเสธ HC09 (อุปกรณ์/อวัยวะเทียม), HC13 (เงื่อนไข HC เพิ่มเติม), IP01 "
        "รวมถึงรายการยา Clopidogrel ถูกปฏิเสธเนื่องจากรหัสยาไม่ตรง Drug Catalogue", 14)

    add_para(doc, "", 6)
    add_para(doc, "ข้อชี้แจง", 15, bold=True)

    add_para(doc, "1. ความจำเป็นทางคลินิก", 14, bold=True)
    add_para(doc,
        "        ผู้ป่วยรายนี้เข้ารับการรักษาด้วยอาการเจ็บหน้าอกรุนแรง ตรวจ EKG พบ ST elevation V1-V4 "
        "ร่วมกับ Troponin สูงกว่าค่าปกติอย่างมีนัยสำคัญ วินิจฉัยเป็น STEMI anterior wall "
        "จึงทำ Primary PCI ซึ่งเป็นมาตรฐานการรักษาตามแนวทางสมาคมแพทย์โรคหัวใจแห่งประเทศไทย "
        "และ ACC/AHA 2025 Guideline for Acute Coronary Syndromes", 14)

    add_para(doc, "2. อุปกรณ์ที่ใช้ (HC09/HC13)", 14, bold=True)
    add_para(doc,
        "        ใช้ Coronary stent 1 ชิ้น จัดซื้อผ่าน GPO VMI/SMI ตามระเบียบ สปสช. "
        "ได้ตรวจสอบและแก้ไข ADP file แล้ว: TYPE=5 ✓, CODE ตรง สปสช. ✓, "
        "Serial/Lot ตรง GPO VMI ✓, จำนวนตรง Cath report ✓", 14)

    add_para(doc, "3. รายการยา Clopidogrel", 14, bold=True)
    add_para(doc,
        "        ตรวจพบว่ารหัสยาใน HIS ไม่ตรงกับ TMT ใน Drug Catalogue สปสช. "
        "ได้แก้ไข mapping HospDrugCode → TMTID เรียบร้อยแล้ว", 14)

    add_para(doc, "4. ข้อมูลที่แก้ไข", 14, bold=True)
    add_para(doc,
        "        แก้ไข ADP file (อุปกรณ์) และ DRU file (ยา) ครบถ้วน จัดส่งพร้อมหนังสือฉบับนี้", 14)

    add_para(doc, "", 6)
    add_para(doc, "เอกสารแนบ", 14, bold=True)
    attachments = [
        "สำเนาเวชระเบียนผู้ป่วยใน",
        "Cardiac Catheterization Report",
        "ผล EKG (ก่อนและหลัง PCI)",
        "ผลตรวจ Troponin",
        "Procedure Note",
        "GPO VMI record (Lot/Serial confirmation)",
        "แฟ้ม ADP ที่แก้ไขแล้ว",
        "แฟ้ม DRU ที่แก้ไข mapping แล้ว",
        "ข้อมูล 16 แฟ้มที่แก้ไขแล้ว (.ecd)",
    ]
    for i, item in enumerate(attachments, 1):
        add_para(doc, f"   {i}. {item}", 13)

    add_para(doc, "", 6)
    add_para(doc,
        "        จึงเรียนมาเพื่อโปรดพิจารณาทบทวนผลการตรวจสอบ "
        "และขอให้ดำเนินการจ่ายชดเชยค่าบริการตามหลักเกณฑ์ที่กำหนด จะเป็นพระคุณยิ่ง", 14)

    add_para(doc, "", 20)
    add_para(doc, "ขอแสดงความนับถือ", 14, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "", 30)
    add_para(doc, "(ลงนาม) .............................................", 14, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "(................................................................)", 14, align=WD_ALIGN_PARAGRAPH.CENTER)
    add_para(doc, "ตำแหน่ง ผู้อำนวยการโรงพยาบาลพญาไทศรีราชา", 14, align=WD_ALIGN_PARAGRAPH.CENTER)

    # Save
    doc.save(output_path)
    size = os.path.getsize(output_path)
    print(f"✅ Full Report สร้างเสร็จ: {output_path}")
    print(f"📄 ขนาด: {size:,} bytes")
    print(f"📋 เนื้อหา:")
    print(f"   Part 1: Claim Check Result (8 Checkpoints + Score)")
    print(f"   Part 2: Deny Analysis (Root Cause + Action Plan + Revenue Impact)")
    print(f"   Part 3: Appeal Letter (หนังสืออุทธรณ์พร้อมส่ง)")


if __name__ == "__main__":
    import sys
    output = sys.argv[1] if len(sys.argv) > 1 else "docs/CathLab_Report_AN69-03556.docx"
    generate_full_report(output)
